export const LOGIN = "LOGIN";

//APLICATIONS
export const CHANGE_THEME = "CHANGE_THEME";
export const CHANGE_FONT = "CHANGE_FONT";
export const FORCE_APPEARANCE = "FORCE_APPEARANCE";
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";

//PROFILE
export const SET_LOGIN = "SET_LOGIN";
